version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-1234}"]
    volumes:
      - redis_data:/data
    networks:
      - rate-limiter-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-1234}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - rate-limiter-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  rate-limiter-network:
    driver: bridge